# Generated by Django 4.0.6 on 2022-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='entered_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='name',
            name='exited_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
