# Generated by Django 4.0.6 on 2022-07-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0002_alter_name_entered_date_alter_name_exited_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exprience',
            new_name='Experience',
        ),
    ]
