# Generated by Django 4.0.6 on 2022-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0007_alter_person_entered_date_alter_person_exited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='entered_date',
            field=models.DateField(verbose_name='date entered'),
        ),
        migrations.AlterField(
            model_name='person',
            name='exited_date',
            field=models.DateField(blank=True, null=True, verbose_name='date exited'),
        ),
    ]
