# Generated by Django 4.0.6 on 2022-08-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_parent'),
        ('team_member', '0008_alter_person_entered_date_alter_person_exited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
